name: Build and Push Spark Image

# on:
#   release:
#     types: [published]

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Tag for spark image'


jobs:
  build-spark-image:
    runs-on: ubuntu-latest
    env:
      SPARK_IMAGE: miaymzheng/spark_etl_mia
    
    steps:
    - name: Print tag
      run: echo "SPARK_IMAGE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
    
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.SPARK_IMAGE }}:${{ env.SPARK_IMAGE_TAG }}
